import type { MarketingDetailPageProps } from "@/components/marketing/marketing-detail-page";

export const marketingLegalSlugs = ["privacy-policy", "terms-and-conditions"] as const;

export type MarketingLegalSlug = (typeof marketingLegalSlugs)[number];

export const marketingLegalContent: Record<MarketingLegalSlug, MarketingDetailPageProps> = {
  "privacy-policy": {
    badge: "Privacy policy",
    title: "Privacy Policy for OrderPilot",
    description:
      "This Privacy Policy explains how OrderPilot collects, uses, stores, and protects information when distributor teams use our order-intake, review, and ERP handoff workflow.",
    stats: [
      { label: "Policy scope", value: "10 sections", detail: "Covers operational data, support interactions, legal rights, retention, and security practices in customer-ready language." },
      { label: "Data categories", value: "Business focused", detail: "OrderPilot is designed for business workflow data such as customer orders, attachments, mailbox metadata, and account records." },
      { label: "Buyer clarity", value: "Practical", detail: "This policy is written to help operations, IT, and legal reviewers understand how OrderPilot handles information in real use." },
    ],
    outcomes: [
      { title: "Operational transparency", text: "Customers can see what business information OrderPilot processes and why that processing is necessary to deliver the service." },
      { title: "Security alignment", text: "The policy explains how access, retention, and incident handling support the operational control model presented across the rest of the site." },
      { title: "Customer rights clarity", text: "Prospective and current customers can understand what choices, requests, and review rights may apply to their information." },
    ],
    sections: [
      { eyebrow: "01 · Overview", title: "What this Privacy Policy covers", text: "This policy applies to information collected through the OrderPilot website, product workspace, support interactions, and rollout conversations. It is intended for business customers evaluating or using OrderPilot in connection with distributor order operations.", bullets: ["Covers website, product, and support interactions", "Applies to customer evaluation and active service use", "Focuses on business workflow information rather than consumer social data"] },
      { eyebrow: "02 · Information we collect", title: "Categories of information processed by OrderPilot", text: "OrderPilot may process account details, workspace configuration data, mailbox connection metadata, uploaded files, extracted order fields, reviewer actions, billing records, and communications with our team. Depending on customer usage, some files or messages may include names, work contact details, shipping details, or other information contained in business order documents.", bullets: ["Account and workspace setup information", "Operational order content, attachments, and extracted fields", "Billing, audit, and support communication records"] },
      { eyebrow: "03 · How we use information", title: "Why OrderPilot uses collected information", text: "We use information to provide the service, authenticate users, connect mailboxes, extract and structure order content, enable reviewer workflow, support ERP handoff readiness, respond to support requests, improve product reliability, and meet contractual, legal, or security obligations.", bullets: ["Deliver and secure the product workflow", "Support customer onboarding and troubleshooting", "Maintain service performance, safety, and compliance obligations"] },
      { eyebrow: "04 · Product workflow processing", title: "How customer order data is handled in the workflow", text: "When a customer connects a shared mailbox or uploads order files, OrderPilot processes that content to identify order-relevant information, generate structured drafts, route exceptions, and maintain reviewer context. We process customer content only to provide and improve the business workflow authorized by the customer organization.", bullets: ["Mailbox and file content are processed to generate structured drafts", "Reviewer actions and approval notes stay tied to the order record", "Processing is limited to providing the customer-authorized workflow"] },
      { eyebrow: "05 · Sharing and service providers", title: "When information may be shared", text: "OrderPilot may share information with trusted infrastructure, billing, authentication, communications, and integration providers as needed to operate the service. We may also disclose information when required by law, to protect rights and security, or in connection with a business transaction such as a merger or acquisition.", bullets: ["Service providers may support hosting, billing, auth, and integrations", "Disclosure may occur for legal or security reasons", "We do not position customer operational data as advertising inventory"] },
      { eyebrow: "06 · Data retention", title: "How long information is retained", text: "We retain information for as long as needed to provide the service, maintain security and audit trails, resolve disputes, comply with legal obligations, and support legitimate business operations. Retention may vary depending on the type of data, customer configuration, contractual commitments, and legal requirements.", bullets: ["Retention depends on business need and legal obligation", "Operational history may be retained for audit and support purposes", "Deletion timing can vary based on customer and regulatory context"] },
      { eyebrow: "07 · Security practices", title: "How OrderPilot protects information", text: "We use reasonable administrative, technical, and organizational measures designed to protect information against unauthorized access, loss, misuse, or disclosure. No service can guarantee absolute security, but OrderPilot is designed so access control, workflow approvals, and system accountability remain visible and reviewable.", bullets: ["Access is controlled through authenticated workspace experiences", "Security safeguards are designed around business workflow risk", "Absolute security cannot be guaranteed, but protections are actively maintained"] },
      { eyebrow: "08 · International and legal considerations", title: "Regional rights and legal review", text: "Depending on where a customer or individual is located, privacy laws may provide rights related to access, correction, deletion, restriction, objection, portability, or complaint. OrderPilot will review applicable requests in light of the customer relationship, system role, and governing legal requirements.", bullets: ["Rights may vary by jurisdiction", "Requests are assessed within the business-customer context", "Legal obligations and security requirements may affect response scope"] },
      { eyebrow: "09 · Contact and requests", title: "How to contact us about privacy", text: "Customers or authorized representatives may contact OrderPilot regarding privacy questions, policy interpretation, access requests, or security concerns. We may require reasonable verification before acting on certain requests in order to protect customer data and account integrity.", bullets: ["Privacy inquiries can be directed to our team", "Verification may be required before fulfilling certain requests", "Business account context may shape how requests are handled"] },
      { eyebrow: "10 · Policy updates", title: "How we handle changes to this policy", text: "We may update this Privacy Policy from time to time to reflect product changes, legal developments, operational improvements, or updated business practices. Material updates may be posted through the website, the product, or other customer communications as appropriate.", bullets: ["Policy updates may reflect product or legal changes", "The latest posted version governs going forward", "Customers should review the policy periodically during ongoing use"] },
    ],
    faqItems: [
      { question: "Does OrderPilot process customer order emails and attachments?", answer: "Yes. If a customer enables mailbox or file-based workflows, OrderPilot may process order emails, attachments, and related business content to generate structured drafts and support reviewer decisions." },
      { question: "Does this policy apply to website visitors as well as product users?", answer: "Yes. It covers website interactions, product use, and business communications with OrderPilot, though the specific data involved can differ by context." },
      { question: "Can customers ask about deletion or access?", answer: "Yes. We review reasonable requests in light of applicable law, the customer relationship, and the need to preserve security, audit history, or legal compliance." },
      { question: "Does OrderPilot sell customer data for advertising?", answer: "This policy is written around business service delivery, infrastructure operations, support, and legal obligations—not around monetizing customer operational data as advertising inventory." },
      { question: "How should legal or security teams use this page?", answer: "They can use it as a customer-facing summary of how OrderPilot handles operational information, then follow up with more detailed diligence questions as needed." },
      { question: "Where should privacy questions be sent?", answer: "Customers may contact OrderPilot through the business contact routes provided on the site for privacy, security, and rollout-related questions." },
    ],
    primaryCta: { label: "Contact OrderPilot", href: "/contact" },
    secondaryCta: { label: "Review terms", href: "/terms-and-conditions" },
    testimonialsTitle: "Why buyers value clear privacy language during evaluation.",
    testimonialsDescription: "Privacy review moves faster when the policy is written in operationally credible language that aligns with the product workflow buyers have already seen.",
  },
  "terms-and-conditions": {
    badge: "Terms & conditions",
    title: "Terms and Conditions for OrderPilot",
    description:
      "These Terms and Conditions describe the legal framework for accessing the OrderPilot website, evaluating the service, and using the OrderPilot platform as a business customer.",
    stats: [
      { label: "Terms coverage", value: "10 sections", detail: "Addresses access, acceptable use, customer responsibilities, payment, intellectual property, warranties, and liability topics." },
      { label: "Commercial focus", value: "B2B", detail: "These terms are written for business customers using OrderPilot as part of distributor operations and workflow management." },
      { label: "Plain-language goal", value: "Readable", detail: "The page is detailed enough for evaluation while staying customer-centric and easier to understand than boilerplate alone." },
    ],
    outcomes: [
      { title: "Clear business expectations", text: "Customers can understand the responsibilities associated with using the website and the product during evaluation and ongoing service use." },
      { title: "Aligned rollout terms", text: "The terms complement the marketing and product positioning by clarifying who controls data, access, approvals, and account use." },
      { title: "Legal review readiness", text: "Stakeholders can use this page as a practical starting point for contractual and procurement review discussions." },
    ],
    sections: [
      { eyebrow: "01 · Acceptance", title: "Agreement to these Terms", text: "By accessing the OrderPilot website, requesting a demo, creating an account, or using the OrderPilot platform, the customer agrees to these Terms and Conditions. If a user is acting on behalf of an organization, that user represents they have authority to bind the organization to these terms.", bullets: ["Use of the site or service indicates agreement", "Users may bind their organization if authorized", "Customers who do not agree should not use the service"] },
      { eyebrow: "02 · Service scope", title: "What OrderPilot provides", text: "OrderPilot provides software and related services designed to help distributor operations teams capture inbound orders, structure draft data, support exception review, and improve ERP handoff readiness. Specific functionality may vary by plan, rollout scope, configuration, and integration status.", bullets: ["Service availability can vary by plan and setup", "Functionality may depend on integrations and customer configuration", "The product is positioned as an operational workflow service"] },
      { eyebrow: "03 · Customer responsibilities", title: "What customers are responsible for", text: "Customers are responsible for maintaining the accuracy of account information, managing authorized users, securing local systems and credentials, reviewing generated drafts before business use where appropriate, and ensuring their use of the service complies with applicable laws, contractual obligations, and internal policies.", bullets: ["Customers manage their own authorized personnel", "Customers remain responsible for internal operational decisions", "Compliance with law and internal policy remains the customer’s obligation"] },
      { eyebrow: "04 · Acceptable use", title: "Restrictions on misuse", text: "Customers may not use OrderPilot in ways that violate law, infringe rights, compromise security, reverse engineer protected portions of the service where prohibited, interfere with platform integrity, or use the product to transmit harmful, fraudulent, or abusive content. OrderPilot may suspend or restrict access when needed to protect the service or other customers.", bullets: ["Illegal, abusive, or harmful use is prohibited", "Security interference and platform misuse are prohibited", "Access may be restricted to protect the service and its users"] },
      { eyebrow: "05 · Fees and billing", title: "Commercial terms and payments", text: "Paid use of OrderPilot may be subject to subscription fees, plan-based limits, renewal terms, and applicable taxes. Billing timing, pricing, and commercial scope may be defined by the selected plan, customer order form, or separate commercial agreement. Failure to pay may result in suspension or limitation of service access.", bullets: ["Fees may depend on plan and commercial agreement", "Taxes and renewals may apply where relevant", "Non-payment may affect access to the service"] },
      { eyebrow: "06 · Intellectual property", title: "Ownership of the service and customer content", text: "OrderPilot retains ownership of the software, website, service materials, branding, and related intellectual property, except as otherwise agreed in writing. Customers retain rights in their own content and operational materials submitted to the service, subject to the rights needed for OrderPilot to provide and support the service.", bullets: ["OrderPilot owns the service and its underlying materials", "Customers retain rights in their own submitted content", "Service-use rights are limited to what is needed to operate and support the product"] },
      { eyebrow: "07 · Availability and changes", title: "Service updates, maintenance, and evolution", text: "OrderPilot may update, enhance, modify, or discontinue features from time to time in order to improve security, usability, reliability, or commercial fit. Reasonable maintenance windows, operational changes, or roadmap updates may affect how specific capabilities appear over time.", bullets: ["The service may evolve over time", "Maintenance and updates may affect feature presentation", "Product improvement does not guarantee every feature remains unchanged"] },
      { eyebrow: "08 · Warranties and disclaimers", title: "Important service disclaimers", text: "Except to the extent expressly stated in a binding written agreement, the website and service are provided on an as-available basis. OrderPilot does not guarantee uninterrupted operation, error-free performance, or suitability for every customer use case. Customers are expected to evaluate the service within their own business, legal, and technical context.", bullets: ["Service may have limitations and evolving capabilities", "Absolute uptime and error-free use are not guaranteed", "Customers should evaluate fit for their own environment"] },
      { eyebrow: "09 · Liability and indemnity", title: "Limits on legal exposure", text: "To the maximum extent permitted by applicable law, OrderPilot’s liability may be limited for indirect, incidental, consequential, special, exemplary, or punitive damages, as well as for lost profits, revenue, goodwill, or data arising from or related to use of the service. Customers may also be responsible for claims arising from their misuse of the service or violation of these terms.", bullets: ["Certain categories of damages may be excluded or limited", "Customers may bear responsibility for misuse-related claims", "Applicable law may affect how limitations are enforced"] },
      { eyebrow: "10 · Governing terms and contact", title: "How disputes, updates, and contact are handled", text: "These terms may be updated periodically, and the latest posted version will apply going forward unless a separate written agreement states otherwise. Questions about the terms, procurement review, or commercial discussions may be directed to OrderPilot through the contact channels provided on the site. Governing law and dispute procedures may also be addressed in a separate customer agreement where applicable.", bullets: ["Terms may be updated from time to time", "Separate written agreements may control specific commercial relationships", "Customers can contact OrderPilot with procurement or legal questions"] },
    ],
    faqItems: [
      { question: "Do these terms apply during evaluation as well as paid use?", answer: "Yes. They are intended to frame access to the website, demos, account creation, and ongoing use of the OrderPilot service unless superseded by a separate written agreement." },
      { question: "Who owns the customer’s order data?", answer: "Customers retain rights in their own content, while OrderPilot retains rights in the software, website, and related service materials, subject to any separate contractual arrangement." },
      { question: "Can features change over time?", answer: "Yes. OrderPilot may improve, modify, or retire aspects of the service as part of ongoing product, security, and operational development." },
      { question: "Are there limits on liability?", answer: "Yes. These terms describe categories of damages that may be limited or excluded to the extent permitted by law, though exact treatment can depend on applicable law and any separate agreement." },
      { question: "What if a customer has a separate order form or contract?", answer: "A separate written agreement may govern specific commercial, legal, or service terms for that customer relationship." },
      { question: "Where should procurement or legal teams send questions?", answer: "They can contact OrderPilot through the site’s contact routes to begin a procurement, commercial, privacy, or legal review conversation." },
    ],
    primaryCta: { label: "Contact OrderPilot", href: "/contact" },
    secondaryCta: { label: "Review privacy policy", href: "/privacy-policy" },
    testimonialsTitle: "Why buyers appreciate terms written for real evaluation workflows.",
    testimonialsDescription: "Procurement and operations conversations move more smoothly when legal pages reflect the actual product, rollout model, and business context buyers are evaluating.",
  },
};